import { supabase, supabaseUrl } from '../lib/supabase';

export const saveToMatchingTable = async (uploadType: 'candidates' | 'employers', jsonContent: any) => {
  if (!jsonContent) return;
  
  // Basic validation to check if URL is configured
  if (!supabaseUrl || supabaseUrl.includes('YOUR_SUPABASE_PROJECT_URL')) {
    console.warn('Supabase URL not configured. Data will only be saved to Local Storage.');
    return;
  }

  try {
    // Assuming 'matching' table exists with columns: id, type, data
    // We insert the entire JSON content as a single record associated with the type
    const { data, error } = await supabase
      .from('matching')
      .insert([
        { 
          type: uploadType, 
          data: jsonContent 
        }
      ])
      .select();

    if (error) {
      // Check specifically for missing table error
      if (error.code === '42P01' || error.message.includes('Could not find the table')) {
        console.error('🚨 SUPABASE TABLE MISSING 🚨');
        console.log('Please run the following SQL in your Supabase SQL Editor to create the table:');
        console.log(`
create table matching (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null,
  data jsonb not null
);
        `);
        alert("Database Error: Table 'matching' is missing. Please check the browser console for the SQL creation script.");
      }
      
      console.error(`Error saving ${uploadType} to matching table:`, error.message, '\nDetails:', error.details || 'None', '\nHint:', error.hint || 'None');
    } else {
      console.log(`${uploadType} JSON saved to matching table successfully`);
    }
  } catch (err) {
    console.error(`Unexpected error saving ${uploadType}:`, err);
  }
};